<?php $this->headTitle('Home'); ?>

<div class="container-fluid">
    <div class="row">

        <div class="well">
            <?php
            $form = $this->form;
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-group">
                <?php
                $element = $form->get('original_url');
                echo $this->formLabel()->openTag(['class' => 'col-sm-2 control-label']);
                echo $this->formLabel($element);
                echo $this->formLabel()->closeTag();
                ?>
                <div class="col-sm-10">
                    <?php
                    echo $this->formText($element);
                    echo $this->formElementErrors($element);
                    ?>
                </div>
            </div>

            <input type="submit" value="submit" class="btn btn-primary"/>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
