<?php $this->headTitle('Home'); ?>

<div class="container-fluid">
    <div class="row">
        <table class="table table-striped table-bordered table-condensed">
            <thead>
            <tr>
                <th>id</th>
                <th>shortened url</th>
                <th>original url</th>
                <th>created</th>
                <th>last updated</th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($this->urls)): ?>
            <?php foreach ($this->urls as $url): ?>
            <tr>
                <td><?php print $url->id ?></td>
                <td><?php print $url->shortened_url ?></td>
                <td><?php print $url->original_url ?></td>
                <td><?php print $url->created ?></td>
                <td><?php print $url->updated ?></td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

